const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="samsamsun789@gmail.com"
global.location="Lahore,Pakistan."
global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "120363023983262391@g.us"
global.DATABASE_URI = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://telegra.ph/file/d5b1c3544fedc23e11a06.jpg" ; // SET LOGO FOR IMAGE 



global.devs = "923184474176" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "2349066658797";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '5',  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "true";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3,
global.disablepm = process.env.DISABLE_PM || "false",
global.MsgsInLog = process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES|| "text",
global.waPresence= process.env.WAPRESENCE ||  "set according to your need" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "923184474176,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd-1.vercel.app"
global.scan = "https://suhail-md-vtsf.onrender.com/";

module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "V.1.2.8",
  caption : process.env.CAPTION || "©sᴜʜᴀɪʟ²²¹-ᴍᴅ" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "Suhail-MD",
  packname: process.env.PACK_NAME || "♥️",
  botname : process.env.BOT_NAME  || "sᴜʜᴀɪʟ-ᴍᴅ",
  ownername:process.env.OWNER_NAME|| "It'x Suhail",

  sessionName:process.env.SESSION_ID || "SUHAIL_13_45_10_09_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgODgsXG4gICAgICAgIDI0NyxcbiAgICAgICAgMjU1LFxuICAgICAgICAyNSxcbiAgICAgICAgNzYsXG4gICAgICAgIDE5MCxcbiAgICAgICAgMjE0LFxuICAgICAgICAxMDAsXG4gICAgICAgIDE2NixcbiAgICAgICAgMjMsXG4gICAgICAgIDc3LFxuICAgICAgICA2LFxuICAgICAgICAxMDgsXG4gICAgICAgIDg2LFxuICAgICAgICA2NSxcbiAgICAgICAgMTkzLFxuICAgICAgICAzMCxcbiAgICAgICAgODAsXG4gICAgICAgIDk3LFxuICAgICAgICAxMDcsXG4gICAgICAgIDk4LFxuICAgICAgICAyMDksXG4gICAgICAgIDE4LFxuICAgICAgICAzMSxcbiAgICAgICAgMTE0LFxuICAgICAgICAzMCxcbiAgICAgICAgMjMxLFxuICAgICAgICAxNjYsXG4gICAgICAgIDIxMSxcbiAgICAgICAgMTUxLFxuICAgICAgICA1LFxuICAgICAgICA4NFxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAyMzYsXG4gICAgICAgIDY2LFxuICAgICAgICAyNTAsXG4gICAgICAgIDgsXG4gICAgICAgIDIzNCxcbiAgICAgICAgNDMsXG4gICAgICAgIDIwOCxcbiAgICAgICAgMTc2LFxuICAgICAgICA3LFxuICAgICAgICA0NCxcbiAgICAgICAgMjQ2LFxuICAgICAgICAxMDIsXG4gICAgICAgIDkyLFxuICAgICAgICAxMDQsXG4gICAgICAgIDY1LFxuICAgICAgICAyOSxcbiAgICAgICAgMTMzLFxuICAgICAgICAyMDMsXG4gICAgICAgIDIwOCxcbiAgICAgICAgMTYsXG4gICAgICAgIDE1MixcbiAgICAgICAgNzgsXG4gICAgICAgIDc0LFxuICAgICAgICAxMzUsXG4gICAgICAgIDE3NCxcbiAgICAgICAgMjIyLFxuICAgICAgICAyMTksXG4gICAgICAgIDIwMixcbiAgICAgICAgNCxcbiAgICAgICAgMTQ1LFxuICAgICAgICA0MixcbiAgICAgICAgOTJcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwicGFpcmluZ0VwaGVtZXJhbEtleVBhaXJcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDE2LFxuICAgICAgICAxODgsXG4gICAgICAgIDEyNSxcbiAgICAgICAgMTc1LFxuICAgICAgICAxNTUsXG4gICAgICAgIDE3NSxcbiAgICAgICAgNTMsXG4gICAgICAgIDc4LFxuICAgICAgICA4LFxuICAgICAgICAxODMsXG4gICAgICAgIDEzOCxcbiAgICAgICAgMzQsXG4gICAgICAgIDIyLFxuICAgICAgICA3MyxcbiAgICAgICAgOTEsXG4gICAgICAgIDEyMCxcbiAgICAgICAgMTU0LFxuICAgICAgICAxODEsXG4gICAgICAgIDI0NSxcbiAgICAgICAgMTk5LFxuICAgICAgICA4NCxcbiAgICAgICAgODQsXG4gICAgICAgIDE3MCxcbiAgICAgICAgMjE2LFxuICAgICAgICAxOTAsXG4gICAgICAgIDI1NCxcbiAgICAgICAgMjUsXG4gICAgICAgIDc1LFxuICAgICAgICAyMDUsXG4gICAgICAgIDI0LFxuICAgICAgICAzOCxcbiAgICAgICAgNzlcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTAzLFxuICAgICAgICAyNDEsXG4gICAgICAgIDE2MCxcbiAgICAgICAgMyxcbiAgICAgICAgMTU3LFxuICAgICAgICAxMTgsXG4gICAgICAgIDcyLFxuICAgICAgICAyMDMsXG4gICAgICAgIDE0NCxcbiAgICAgICAgMjQzLFxuICAgICAgICAxMjIsXG4gICAgICAgIDQyLFxuICAgICAgICA1MixcbiAgICAgICAgNTMsXG4gICAgICAgIDI0OCxcbiAgICAgICAgODMsXG4gICAgICAgIDYxLFxuICAgICAgICAxMjksXG4gICAgICAgIDEwMCxcbiAgICAgICAgMTgzLFxuICAgICAgICAyNTMsXG4gICAgICAgIDcsXG4gICAgICAgIDE1MyxcbiAgICAgICAgMTQxLFxuICAgICAgICAxNzEsXG4gICAgICAgIDIzNyxcbiAgICAgICAgMTQzLFxuICAgICAgICA0MCxcbiAgICAgICAgMzksXG4gICAgICAgIDIwNixcbiAgICAgICAgMjA4LFxuICAgICAgICA0MlxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJzaWduZWRJZGVudGl0eUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTkyLFxuICAgICAgICAxNzgsXG4gICAgICAgIDIwNSxcbiAgICAgICAgMjI1LFxuICAgICAgICAxOTcsXG4gICAgICAgIDcwLFxuICAgICAgICAxMTMsXG4gICAgICAgIDE3NCxcbiAgICAgICAgMjI2LFxuICAgICAgICAxMjEsXG4gICAgICAgIDE0MixcbiAgICAgICAgODIsXG4gICAgICAgIDEyMixcbiAgICAgICAgMTAwLFxuICAgICAgICA0OSxcbiAgICAgICAgNjYsXG4gICAgICAgIDE0OCxcbiAgICAgICAgMzYsXG4gICAgICAgIDEsXG4gICAgICAgIDczLFxuICAgICAgICAxNTYsXG4gICAgICAgIDEzNCxcbiAgICAgICAgOTgsXG4gICAgICAgIDkyLFxuICAgICAgICAxMTYsXG4gICAgICAgIDEwMyxcbiAgICAgICAgMTA4LFxuICAgICAgICAxMzAsXG4gICAgICAgIDczLFxuICAgICAgICAxMDksXG4gICAgICAgIDE4MCxcbiAgICAgICAgNzRcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTU5LFxuICAgICAgICAxMTEsXG4gICAgICAgIDExNixcbiAgICAgICAgNDIsXG4gICAgICAgIDcwLFxuICAgICAgICAxOTQsXG4gICAgICAgIDEyNCxcbiAgICAgICAgMSxcbiAgICAgICAgNTQsXG4gICAgICAgIDcyLFxuICAgICAgICAxOTIsXG4gICAgICAgIDI0NSxcbiAgICAgICAgMjEwLFxuICAgICAgICAyMTYsXG4gICAgICAgIDEyOSxcbiAgICAgICAgMTgxLFxuICAgICAgICAyMTEsXG4gICAgICAgIDI0NSxcbiAgICAgICAgOTUsXG4gICAgICAgIDIzNSxcbiAgICAgICAgMTQ0LFxuICAgICAgICAxMzIsXG4gICAgICAgIDI4LFxuICAgICAgICAxNzQsXG4gICAgICAgIDIxMyxcbiAgICAgICAgMTUwLFxuICAgICAgICAyNDUsXG4gICAgICAgIDE2OSxcbiAgICAgICAgNzcsXG4gICAgICAgIDExNCxcbiAgICAgICAgOTEsXG4gICAgICAgIDEwNlxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJzaWduZWRQcmVLZXlcIjoge1xuICAgIFwia2V5UGFpclwiOiB7XG4gICAgICBcInByaXZhdGVcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICA0OCxcbiAgICAgICAgICAxMjEsXG4gICAgICAgICAgMjA1LFxuICAgICAgICAgIDc2LFxuICAgICAgICAgIDE1MCxcbiAgICAgICAgICAzMCxcbiAgICAgICAgICAxMDYsXG4gICAgICAgICAgMjM4LFxuICAgICAgICAgIDI3LFxuICAgICAgICAgIDY1LFxuICAgICAgICAgIDExNCxcbiAgICAgICAgICAxNzAsXG4gICAgICAgICAgNjksXG4gICAgICAgICAgMTI1LFxuICAgICAgICAgIDE2LFxuICAgICAgICAgIDExMyxcbiAgICAgICAgICAxNzMsXG4gICAgICAgICAgODcsXG4gICAgICAgICAgNTQsXG4gICAgICAgICAgNDMsXG4gICAgICAgICAgMTA0LFxuICAgICAgICAgIDIzNSxcbiAgICAgICAgICAyMDQsXG4gICAgICAgICAgMTMwLFxuICAgICAgICAgIDcyLFxuICAgICAgICAgIDEwNCxcbiAgICAgICAgICAxNTAsXG4gICAgICAgICAgMTI1LFxuICAgICAgICAgIDYsXG4gICAgICAgICAgMTgzLFxuICAgICAgICAgIDE3NyxcbiAgICAgICAgICAxMjdcbiAgICAgICAgXVxuICAgICAgfSxcbiAgICAgIFwicHVibGljXCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgMyxcbiAgICAgICAgICAxNTgsXG4gICAgICAgICAgMjA3LFxuICAgICAgICAgIDg4LFxuICAgICAgICAgIDE0MSxcbiAgICAgICAgICAxNDYsXG4gICAgICAgICAgOTEsXG4gICAgICAgICAgMjEwLFxuICAgICAgICAgIDEzNSxcbiAgICAgICAgICAxNTQsXG4gICAgICAgICAgMjI2LFxuICAgICAgICAgIDIyMCxcbiAgICAgICAgICAxODQsXG4gICAgICAgICAgMTU5LFxuICAgICAgICAgIDI0NCxcbiAgICAgICAgICA1MixcbiAgICAgICAgICAyMCxcbiAgICAgICAgICAyNDMsXG4gICAgICAgICAgMzMsXG4gICAgICAgICAgMTkyLFxuICAgICAgICAgIDEwNixcbiAgICAgICAgICA0MCxcbiAgICAgICAgICAyNDMsXG4gICAgICAgICAgNyxcbiAgICAgICAgICA4OSxcbiAgICAgICAgICAyMDEsXG4gICAgICAgICAgMTMsXG4gICAgICAgICAgMjAwLFxuICAgICAgICAgIDY4LFxuICAgICAgICAgIDM1LFxuICAgICAgICAgIDExMCxcbiAgICAgICAgICA1MVxuICAgICAgICBdXG4gICAgICB9XG4gICAgfSxcbiAgICBcInNpZ25hdHVyZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDg3LFxuICAgICAgICAxOTUsXG4gICAgICAgIDkyLFxuICAgICAgICAyMSxcbiAgICAgICAgODUsXG4gICAgICAgIDYxLFxuICAgICAgICA2MyxcbiAgICAgICAgMTQwLFxuICAgICAgICAyNTMsXG4gICAgICAgIDE3NixcbiAgICAgICAgMjAsXG4gICAgICAgIDExMixcbiAgICAgICAgMjUxLFxuICAgICAgICA0LFxuICAgICAgICAyMTgsXG4gICAgICAgIDExNCxcbiAgICAgICAgMjMzLFxuICAgICAgICAxNTcsXG4gICAgICAgIDI1MyxcbiAgICAgICAgOSxcbiAgICAgICAgNDUsXG4gICAgICAgIDIwOCxcbiAgICAgICAgMjMyLFxuICAgICAgICAyMTMsXG4gICAgICAgIDk0LFxuICAgICAgICAxODQsXG4gICAgICAgIDE1MixcbiAgICAgICAgMzEsXG4gICAgICAgIDE4MyxcbiAgICAgICAgNTksXG4gICAgICAgIDE4NCxcbiAgICAgICAgMjEwLFxuICAgICAgICAyMTksXG4gICAgICAgIDEzOSxcbiAgICAgICAgMjU1LFxuICAgICAgICAxMDMsXG4gICAgICAgIDI0OSxcbiAgICAgICAgMTczLFxuICAgICAgICAxODAsXG4gICAgICAgIDExMixcbiAgICAgICAgMTE1LFxuICAgICAgICAxNTEsXG4gICAgICAgIDgwLFxuICAgICAgICAxMDEsXG4gICAgICAgIDU4LFxuICAgICAgICAxNTgsXG4gICAgICAgIDMsXG4gICAgICAgIDEzNixcbiAgICAgICAgMjQ0LFxuICAgICAgICAyMjAsXG4gICAgICAgIDU5LFxuICAgICAgICA3LFxuICAgICAgICAxODIsXG4gICAgICAgIDE3NixcbiAgICAgICAgODQsXG4gICAgICAgIDI1LFxuICAgICAgICAzOSxcbiAgICAgICAgMyxcbiAgICAgICAgNTksXG4gICAgICAgIDUsXG4gICAgICAgIDIzOCxcbiAgICAgICAgMTIxLFxuICAgICAgICAxNjgsXG4gICAgICAgIDNcbiAgICAgIF1cbiAgICB9LFxuICAgIFwia2V5SWRcIjogMVxuICB9LFxuICBcInJlZ2lzdHJhdGlvbklkXCI6IDk1LFxuICBcImFkdlNlY3JldEtleVwiOiBcIi9Vc0xzd3p5bE9ZaWczcEZuU3E3b2VKb0NUVW94S0Nrc0VaSERyUGY4MTQ9XCIsXG4gIFwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzXCI6IFtcbiAgICB7XG4gICAgICBcImtleVwiOiB7XG4gICAgICAgIFwicmVtb3RlSmlkXCI6IFwiMjM0OTA2NjY1ODc5N0BzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImZyb21NZVwiOiB0cnVlLFxuICAgICAgICBcImlkXCI6IFwiQUMwNDUzRUYzQTFBN0EzMjk2RTFCNjUwQkI2NUI0RDJcIlxuICAgICAgfSxcbiAgICAgIFwibWVzc2FnZVRpbWVzdGFtcFwiOiAxNzI4NDgxNTQ4XG4gICAgfSxcbiAgICB7XG4gICAgICBcImtleVwiOiB7XG4gICAgICAgIFwicmVtb3RlSmlkXCI6IFwiMjM0OTA2NjY1ODc5N0BzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImZyb21NZVwiOiB0cnVlLFxuICAgICAgICBcImlkXCI6IFwiMzUyNERENDJENzYwOEEyRThDNkE3MTc3NkMyNjEyMzNcIlxuICAgICAgfSxcbiAgICAgIFwibWVzc2FnZVRpbWVzdGFtcFwiOiAxNzI4NDgxNTQ4XG4gICAgfVxuICBdLFxuICBcIm5leHRQcmVLZXlJZFwiOiA2MSxcbiAgXCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZFwiOiA2MSxcbiAgXCJhY2NvdW50U3luY0NvdW50ZXJcIjogMSxcbiAgXCJhY2NvdW50U2V0dGluZ3NcIjoge1xuICAgIFwidW5hcmNoaXZlQ2hhdHNcIjogZmFsc2VcbiAgfSxcbiAgXCJkZXZpY2VJZFwiOiBcIkM0RFl6emwzU25XYjh4bU45anVQVFFcIixcbiAgXCJwaG9uZUlkXCI6IFwiNjU0NTc1MjctY2ViZC00NzlhLWEwYmUtOTYxNzAzZmIzOWM2XCIsXG4gIFwiaWRlbnRpdHlJZFwiOiB7XG4gICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgXCJkYXRhXCI6IFtcbiAgICAgIDk4LFxuICAgICAgNzksXG4gICAgICAxNTksXG4gICAgICAxOTUsXG4gICAgICAxMjAsXG4gICAgICA5MixcbiAgICAgIDEzLFxuICAgICAgMjA0LFxuICAgICAgMjU1LFxuICAgICAgNDgsXG4gICAgICAyLFxuICAgICAgMTY1LFxuICAgICAgMTk2LFxuICAgICAgMTc3LFxuICAgICAgMTE0LFxuICAgICAgMjYsXG4gICAgICAxNzUsXG4gICAgICAxMSxcbiAgICAgIDIzLFxuICAgICAgMTY4XG4gICAgXVxuICB9LFxuICBcInJlZ2lzdGVyZWRcIjogdHJ1ZSxcbiAgXCJiYWNrdXBUb2tlblwiOiB7XG4gICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgXCJkYXRhXCI6IFtcbiAgICAgIDE1NCxcbiAgICAgIDIwNyxcbiAgICAgIDEwLFxuICAgICAgMjAxLFxuICAgICAgNjUsXG4gICAgICAxMSxcbiAgICAgIDIxMixcbiAgICAgIDI0OCxcbiAgICAgIDQ5LFxuICAgICAgMjI3LFxuICAgICAgMjIsXG4gICAgICA3LFxuICAgICAgMjksXG4gICAgICAxNDgsXG4gICAgICAzMSxcbiAgICAgIDk1LFxuICAgICAgMTI5LFxuICAgICAgMjI4LFxuICAgICAgMTAyLFxuICAgICAgNTNcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uXCI6IHt9LFxuICBcInBhaXJpbmdDb2RlXCI6IFwiVzVaMVRTUjFcIixcbiAgXCJtZVwiOiB7XG4gICAgXCJpZFwiOiBcIjIzNDkwNjY2NTg3OTc6NkBzLndoYXRzYXBwLm5ldFwiLFxuICAgIFwibGlkXCI6IFwiMTc3NDI5OTE0MTA3OTMyOjZAbGlkXCIsXG4gICAgXCJuYW1lXCI6IFwib2xhZGVqb2FiZHVsbWFsaWsxOTk5XCJcbiAgfSxcbiAgXCJhY2NvdW50XCI6IHtcbiAgICBcImRldGFpbHNcIjogXCJDS2lKeTRJRkVJT1NtcmdHR0FFZ0FDZ0FcIixcbiAgICBcImFjY291bnRTaWduYXR1cmVLZXlcIjogXCJEd2ZqVG02Vm5Lckx3NzAyU2RpZVNaRzNQeEJvSDVxYVp0QjNCVXJ3UGpJPVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZVwiOiBcIm0zTUNCTGdYTmt3SkljZmpJWCtKR1FWR3Y4dlRrekhHVk9pcjJBUTc0U2t5WG9nQTd1cUNUOTJROWFJaE1Yemx3cmxqRFgvOXNXZHphSGZjc2owS0F3PT1cIixcbiAgICBcImRldmljZVNpZ25hdHVyZVwiOiBcIjN5TmlSVStJaUpSY0xNc2RvSjBMZDBQS1k1L2o2NCtKY2NUMEFsRklEWlBpWnd2Yko2R2ZXNFdsRUF6ajRxK2xsQy9mbHpCdWtjU1pjd1FQTVFBbkNBPT1cIlxuICB9LFxuICBcInNpZ25hbElkZW50aXRpZXNcIjogW1xuICAgIHtcbiAgICAgIFwiaWRlbnRpZmllclwiOiB7XG4gICAgICAgIFwibmFtZVwiOiBcIjIzNDkwNjY2NTg3OTc6NkBzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImRldmljZUlkXCI6IDBcbiAgICAgIH0sXG4gICAgICBcImlkZW50aWZpZXJLZXlcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICA1LFxuICAgICAgICAgIDE1LFxuICAgICAgICAgIDcsXG4gICAgICAgICAgMjI3LFxuICAgICAgICAgIDc4LFxuICAgICAgICAgIDExMCxcbiAgICAgICAgICAxNDksXG4gICAgICAgICAgMTU2LFxuICAgICAgICAgIDE3MCxcbiAgICAgICAgICAyMDMsXG4gICAgICAgICAgMTk1LFxuICAgICAgICAgIDE4OSxcbiAgICAgICAgICA1NCxcbiAgICAgICAgICA3MyxcbiAgICAgICAgICAyMTYsXG4gICAgICAgICAgMTU4LFxuICAgICAgICAgIDczLFxuICAgICAgICAgIDE0NSxcbiAgICAgICAgICAxODMsXG4gICAgICAgICAgNjMsXG4gICAgICAgICAgMTYsXG4gICAgICAgICAgMTA0LFxuICAgICAgICAgIDMxLFxuICAgICAgICAgIDE1NCxcbiAgICAgICAgICAxNTQsXG4gICAgICAgICAgMTAyLFxuICAgICAgICAgIDIwOCxcbiAgICAgICAgICAxMTksXG4gICAgICAgICAgNSxcbiAgICAgICAgICA3NCxcbiAgICAgICAgICAyNDAsXG4gICAgICAgICAgNjIsXG4gICAgICAgICAgNTBcbiAgICAgICAgXVxuICAgICAgfVxuICAgIH1cbiAgXSxcbiAgXCJwbGF0Zm9ybVwiOiBcImFuZHJvaWRcIixcbiAgXCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXBcIjogMTcyODQ4MTU0NixcbiAgXCJteUFwcFN0YXRlS2V5SWRcIjogXCJBQUFBQUtXUFwiXG59IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBS1dQLmpzb24iOiAie1wia2V5RGF0YVwiOlwielVFeU1QbS80Y0FLQjBybnl3aDZLOU1uL2pHdlpUMzRiSmZvcWlzVXMvRT1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoxMzQ3NjAxNTc2LFwiY3VycmVudEluZGV4XCI6MSxcImRldmljZUluZGV4ZXNcIjpbMCwxXX0sXCJ0aW1lc3RhbXBcIjpcIjE3Mjg0ODE1NDg2ODZcIn0iCn0=",  // PUT SESSION ID HERE 
  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,

  aitts_Voice_Id : process.env.AITTS_ID || "37",
  ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY || "",
  WORKTYPE: process.env.WORKTYPE||process.env.MODE || "private",
  LANG: process.env.THEME ? process.env.THEME.toUpperCase() : "SUHAIL",



};




























global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
 
